version: '3.8'

services:

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-library
    depends_on:
      - "library-frontend"
      - "library-backend"
  
  library-frontend:
    image: library-frontend-dev
    build:
      context: ./library-frontend/ # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./library-frontend:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=api/
  
  library-backend:
    image: library-backend-dev
    build:
      context: ./library-backend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./library-backend:/usr/src/app
    ports:
      - 4000:4000
    depends_on:
      - "mongo"
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./library-backend/mongo_data:/data/db